In [125]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle 
import pandas as pd 
import numpy as np

In [126]:
#load all train model 
model = load_model('model.h5')
#Load encoder and scaler 
with open('ohe_geo.pkl','rb') as file:
    lable_encoder_geo=pickle.load(file)

with open('ohe_gen.pkl','rb') as file:
    lable_encoder_gen=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [127]:
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [128]:
geo_encoded = lable_encoder_geo.transform([[input_data['Geography']]])
geo_df=pd.DataFrame(geo_encoded,columns=lable_encoder_geo.get_feature_names_out(['Geography']))

c:\Users\dipes\OneDrive\Desktop\ANNRNNproj\annenv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [129]:
geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [130]:
import pandas as pd

input_data = pd.DataFrame([input_data])

input_data = pd.concat(
    [input_data.reset_index(drop=True), geo_df.reset_index(drop=True)],
    axis=1
)

In [131]:
input_data

   CreditScore Geography  ... Geography_Germany  Geography_Spain
0          600    France  ...               0.0              0.0

[1 rows x 13 columns]

In [132]:
input_data['Gender']=lable_encoder_gen.transform(input_data['Gender'])

In [133]:
input_data

   CreditScore Geography  ...  Geography_Germany  Geography_Spain
0          600    France  ...                0.0              0.0

[1 rows x 13 columns]

In [134]:
input_data.drop(columns=["Geography"], inplace=True)

In [135]:
# concatination with one hot encoded data 
# input_data=pd.concat([input_data.drop("Geography",axis=1),geo_df],axis=1)

In [136]:
input_data

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [137]:
#scaling the input data 
input_scaled=scaler.transform(input_data)

In [139]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [142]:
#predict churn 
prediction=model.predict(input_scaled)
print(100*prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
[[3.3817909]]

In [143]:
prediction_proba=prediction[0][0]

In [147]:
if prediction_proba > 0.5:
    print("the customer is likely to churn")
else:
    print("the customer is not likely to churn")

the customer is not likely to churn